import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { checkClientOrAdminAuth } from "../_shared/auth.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// 4 client-facing onboarding gates — prepended to ALL tiers
// Order rationale:
//   1. Confirm info first (we need this before anything)
//   2. Upload brand assets — no dependency on a call anymore, can happen right away
//   3. Connect social accounts — after brand assets are in
//   4. Approve first content — after strategy is aligned
// Kickoff call (Calendly) step removed for now -- see git history to restore.
const ONBOARDING_STEPS = [
  {
    step_number: 1,
    step_name: "Confirm Business Information",
    task_type: "client_form",
    depends_on: null,
    payload: {
      form_type: "business_info",
      fields: ["business_name", "website_url", "phone", "address", "industry", "target_audience", "main_competitors"],
    },
  },
  {
    step_number: 2,
    step_name: "Upload Brand Assets",
    task_type: "client_upload",
    depends_on: 1,
    payload: {
      required: ["logo_primary"],
      optional: ["logo_dark", "brand_colors", "font_guidelines"],
    },
  },
  {
    step_number: 3,
    step_name: "Connect Social Accounts",
    task_type: "client_oauth",
    depends_on: 2,
    payload: {
      platforms: ["linkedin", "facebook", "instagram", "twitter"],
      minimum_required: 1,
    },
  },
  {
    step_number: 4,
    step_name: "Approve Your First Content Draft",
    task_type: "client_approval",
    depends_on: 3,
    payload: { content_type: "linkedin_post" },
  },
];

const ONBOARDING_OFFSET = ONBOARDING_STEPS.length; // 4

// Automation steps — original step_numbers start at 1 but will be offset by 4.
// No "Publish X" step here anymore (was n8n_post_social/n8n_post_blog, routed
// to trigger-n8n) -- actual publishing already happens on its own continuous
// schedule (auto-schedule-content -> content_calendar -> publish-scheduled-
// content), not as a one-time onboarding checklist gate, and n8n has no real
// role left in it for the platforms this covers (see git history for the
// removal).
//
// This chain is SETUP ONLY, not a content burst. It used to also include a
// second blog article, ad copy, a nurture sequence, a retention sequence, and
// both a quarterly and monthly report -- all one-time, all firing back-to-
// back within the same ~30 minutes once step 4 (client_approval) unlocks the
// chain, since process-agent-jobs dequeues every minute and each step
// auto-unlocks the next the instant it completes. Two problems with that:
// content pieces were quota borrowed from the tier's actual monthly
// allowance (a client's plan promises "2 blogs/month"; onboarding handed
// them 2 blogs in the first 10 minutes, then nothing for the rest of the
// month), and both reports were generated with zero real history behind
// them -- structurally near-empty ("No active plans", "No logged activity").
// Reports and the ongoing content cadence belong entirely to their real
// recurring cadence (fill-scheduled-content, monthly-client-reports/weekly-
// client-reports) once there's actual data to report on. The GBP post stays
// as the one immediate, tangible "here's what this looks like" proof --
// everything else here is analysis/config that legitimately IS a day-one
// concern (audit the current state, extract brand context, seed the social
// strategy) rather than content output.
const FOUNDATION_STEPS = [
  { step_number: 1, step_name: "Analyze current website performance", task_type: "website_analysis", depends_on: null },
  { step_number: 2, step_name: "Run basic SEO audit", task_type: "seo_audit", depends_on: 1 },
  { step_number: 3, step_name: "Generate marketing gap report", task_type: "gap_report", depends_on: 2 },
  // Used to be a fire-and-forget background fetch with no tracking, no
  // depends_on, and no guarantee it finished before any content/strategy
  // step ran off default/empty brand context. Now a real step everything
  // brand-sensitive waits on.
  { step_number: 4, step_name: "Extract brand assets from website", task_type: "brand_extraction", depends_on: 3 },
  { step_number: 5, step_name: "Create Google Business Profile post", task_type: "content", depends_on: 4, payload: { content_type: "gbp_post" } },
  // Previously only ever generated by the weekly client-context-refresh cron
  // (or a manual trigger with no UI) -- a brand-new client's Social agent
  // could sit at "Setting Up" for up to a week with zero way to speed it up,
  // unlike SEO which gets a real audit immediately as step 2 above.
  { step_number: 6, step_name: "Generate social media strategy", task_type: "social_strategy", depends_on: 4 },
];

// Tier no longer changes the onboarding chain itself -- every tier gets the
// same setup steps above. What tier actually changes now lives entirely in
// the ongoing cadence (tierPolicy.ts: content volume, prospecting, report
// frequency), which is the correct place for it since that's what a client
// is actually paying for on a monthly basis, not a bigger one-time burst.
const GROWTH_EXTRA: typeof FOUNDATION_STEPS = [];
const TRANSFORMATION_EXTRA: typeof FOUNDATION_STEPS = [];

function renumberAutomationSteps(steps: any[]) {
  return steps.map((s) => ({
    ...s,
    step_number: s.step_number + ONBOARDING_OFFSET,
    depends_on: s.depends_on != null ? s.depends_on + ONBOARDING_OFFSET : ONBOARDING_OFFSET, // first automation step depends on last onboarding step
  }));
}

function getStepsForTier(tier: string) {
  const t = tier.toLowerCase();
  let automationSteps: any[];
  if (t === "transformation") {
    automationSteps = [...FOUNDATION_STEPS, ...GROWTH_EXTRA, ...TRANSFORMATION_EXTRA];
  } else if (t === "growth") {
    automationSteps = [...FOUNDATION_STEPS, ...GROWTH_EXTRA];
  } else {
    automationSteps = [...FOUNDATION_STEPS];
  }

  // Set initial status for onboarding steps
  const onboarding = ONBOARDING_STEPS.map((s, i) => ({
    ...s,
    status: i === 0 ? "pending" : "locked",
  }));

  return [...onboarding, ...renumberAutomationSteps(automationSteps)];
}

/** Add `businessDays` working days to `start`, skipping Sat/Sun. */
function addBusinessDays(start: Date, businessDays: number): Date {
  const d = new Date(start);
  let added = 0;
  while (added < businessDays) {
    d.setDate(d.getDate() + 1);
    const dow = d.getDay();
    if (dow !== 0 && dow !== 6) added++;
  }
  return d;
}

function toDateStr(d: Date): string {
  return d.toISOString().split("T")[0];
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  let client_id: string | undefined;

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const body = await req.json();
    client_id = body.client_id;
    if (!client_id) {
      return new Response(JSON.stringify({ error: "client_id required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const auth = await checkClientOrAdminAuth(req, supabase, client_id, body.password);
    if (!auth.authorized) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get client tier + website_url for brand extraction
    const { data: client, error: clientErr } = await supabase
      .from("client_accounts")
      .select("tier, website_url")
      .eq("id", client_id)
      .single();

    if (clientErr || !client) {
      return new Response(JSON.stringify({ error: "Client not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Check for existing active workflow
    const { data: existing } = await supabase
      .from("client_workflows")
      .select("id")
      .eq("client_id", client_id)
      .eq("status", "active")
      .maybeSingle();

    if (existing) {
      return new Response(
        JSON.stringify({ error: "Active workflow already exists", workflow_id: existing.id }),
        { status: 409, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Read Calendly URL from admin_settings (falls back to hardcoded default)
    const { data: calendlySetting } = await supabase
      .from("admin_settings")
      .select("value")
      .eq("key", "calendly_url")
      .maybeSingle();
    const calendlyUrl = calendlySetting?.value || "https://calendly.com/baker-orangedoor";

    const steps = getStepsForTier(client.tier);

    // Inject the live Calendly URL into the kickoff step payload
    const calendarStep = steps.find((s: any) => s.task_type === "client_calendar");
    if (calendarStep) calendarStep.payload = { ...calendarStep.payload, calendar_url: calendlyUrl };

    // Create workflow
    const { data: workflow, error: wfError } = await supabase
      .from("client_workflows")
      .insert({
        client_id,
        workflow_name: `${client.tier}_workflow`,
        current_step: 1,
        total_steps: steps.length,
        status: "active",
      })
      .select()
      .single();

    if (wfError) throw new Error(`Failed to create workflow: ${wfError.message}`);

    // Calculate estimated_completion dates
    const today = new Date();
    const estimatedDates: string[] = [];
    for (let i = 0; i < steps.length; i++) {
      const s = steps[i];
      // Onboarding steps (client-driven) get 1 business day each
      const isOnboarding = s.task_type.startsWith("client_");
      const bizDays = isOnboarding ? 1 : 2;
      if (i === 0) {
        estimatedDates.push(toDateStr(addBusinessDays(today, bizDays)));
      } else {
        const prevDate = new Date(estimatedDates[i - 1] + "T00:00:00");
        const startFrom = new Date(prevDate);
        startFrom.setDate(startFrom.getDate() + 1);
        estimatedDates.push(toDateStr(addBusinessDays(startFrom, bizDays)));
      }
    }

    // Seed steps
    const rows = steps.map((s: any, i: number) => ({
      step_number: s.step_number,
      step_name: s.step_name,
      task_type: s.task_type,
      depends_on: s.depends_on,
      payload: s.payload || null,
      status: s.status || "locked",
      workflow_id: workflow.id,
      client_id,
      estimated_completion: estimatedDates[i],
    }));

    const { error: stepsError } = await supabase.from("workflow_steps").insert(rows);
    if (stepsError) throw new Error(`Failed to seed steps: ${stepsError.message}`);

    // Seed client_onboarding record so admin panels show this client immediately
    const { error: onboardingErr } = await supabase
      .from("client_onboarding")
      .insert({ client_account_id: client_id, current_step: 1 });
    // 23505 = unique violation (already exists) — safe to ignore
    if (onboardingErr && onboardingErr.code !== "23505") {
      console.error("Failed to seed client_onboarding:", onboardingErr.message);
    }

    // Brand extraction used to fire here as an untracked background fetch --
    // now it's the "Extract brand assets from website" step above, run
    // through the normal automation queue like everything else, so
    // content/strategy steps can actually depends_on it finishing instead of
    // racing it. Project generation is not auto-triggered here either --
    // bootstrap_client_projects (seeded via workflowUnlock.ts at onboarding
    // completion) owns automatic seo/social/prospect shells; custom/LLM
    // projects are admin-triggered only (ProjectSetupWizard.tsx).

    return new Response(
      JSON.stringify({
        success: true,
        workflow_id: workflow.id,
        tier: client.tier,
        total_steps: steps.length,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("seed-tier-workflow error:", error);

    try {
      const supabase = createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
      );
      await supabase.from("automation_alerts").insert({
        alert_type: "function_error",
        severity: "error",
        title: "Error in seed-tier-workflow",
        message: error instanceof Error ? error.message : "Unknown error",
        source: "seed-tier-workflow",
        source_id: client_id ?? undefined,
        metadata: {
          function_name: "seed-tier-workflow",
          client_id: client_id ?? null,
          error_message: error instanceof Error ? error.message : "Unknown error",
          timestamp: new Date().toISOString(),
        },
      });
    } catch (_alertErr) {
      console.error("Failed to log alert:", _alertErr);
    }

    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
