-- Drop the existing check constraint
ALTER TABLE automation_jobs DROP CONSTRAINT automation_jobs_job_type_check;

-- Add updated check constraint with all supported job types
ALTER TABLE automation_jobs ADD CONSTRAINT automation_jobs_job_type_check CHECK (job_type = ANY (ARRAY[
  'weekly_report'::text,
  'monthly_report'::text,
  'content_generation'::text,
  'seo_audit'::text,
  'competitor_analysis'::text,
  'generate_social_posts'::text,
  'generate_blog_post'::text,
  'generate_email_campaign'::text,
  'generate_seo_recommendations'::text,
  'create_analytics_dashboard'::text,
  'generate_ad_copy'::text,
  'build_review_funnel'::text,
  'create_lead_magnet'::text,
  'setup_email_automation'::text,
  'website_audit'::text,
  'keyword_research'::text,
  'backlink_analysis'::text,
  'social_media_audit'::text,
  'conversion_optimization'::text,
  'brand_voice_guide'::text,
  'generate_client_report'::text,
  'add_segmentation_logic_to_funnel_steps'::text,
  'build_renewal_reminder_sequence'::text,
  'build_review_to_case_study_workflow'::text,
  'custom'::text,
  'email_sequence'::text,
  'generate_report'::text,
  'run_seo_audit'::text,
  'report'::text,
  -- New job types from edge function
  'send_intake_form'::text,
  'add_to_crm'::text,
  'schedule_kickoff'::text,
  'run_page_speed_test'::text,
  'create_google_review_link'::text,
  'create_review_qr_code'::text,
  'setup_review_automation'::text,
  'send_review_scripts'::text,
  'create_kpi_dashboard'::text,
  'run_keyword_gap_analysis'::text,
  'setup_lead_automations'::text,
  'setup_retargeting_audiences'::text,
  'setup_retention_automations'::text,
  'generate_monthly_report'::text
]));