// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined)
  || "https://axbeaqpjyzzmbvyaofbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)
  || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4YmVhcXBqeXp6bWJ2eWFvZmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMDk3NTEsImV4cCI6MjA5MjU4NTc1MX0.RLbpE81uPfdEKW1k-Hc-iyiEfyi6R15OGSMl2TTyf1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// On a non-2xx response the SDK's FunctionsHttpError.message is the useless
// "Edge Function returned a non-2xx status code" — the function's actual
// `{ error: "..." }` body is only reachable via error.context. Most call
// sites surface error.message directly, so rewrite it here, once, with the
// real message. Reads a clone, so error.context stays consumable for call
// sites that parse the body themselves (getEdgeErrorMessage).
const originalInvoke = supabase.functions.invoke.bind(supabase.functions);
supabase.functions.invoke = (async (name: string, options?: Parameters<typeof originalInvoke>[1]) => {
  const result = await originalInvoke(name, options);
  const ctx = (result.error as { context?: Response } | null)?.context;
  if (result.error && ctx && typeof ctx.clone === "function") {
    try {
      const body = await ctx.clone().json();
      const msg = body?.error ?? body?.message;
      if (typeof msg === "string" && msg) result.error.message = msg;
    } catch {
      // body not JSON — keep the SDK's default message
    }
  }
  // Extraction above only works for a real HTTP response (context present,
  // JSON body). Whatever's left over -- a genuine network failure, an
  // opaque/non-JSON body, or the SDK's own generic non-2xx placeholder --
  // never surface verbatim; callers that skip getEdgeErrorMessage and read
  // error.message directly still get something a user can read.
  if (result.error?.message && /non-2xx|edge function returned/i.test(result.error.message)) {
    result.error.message = "Something went wrong completing that request. Please try again — if this persists, contact support.";
  }
  return result;
}) as typeof supabase.functions.invoke;